export const data = [
    {
      key: "1",
      employeeName: "Aditya Garikapati",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Software Engineer",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-04-12",
      amountPayable: 13124,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "2",
      employeeName: "Aryan Joshi",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Consultant",
      device: "iPhone 15",
      addson: 2,
      requestedOn: "2024-04-10",
      amountPayable: 19354,
      amountDurationInMonths: 6,
      status: "pending",
    },
    {
      key: "3",
      employeeName: "Sunita Reddy",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Business Analyst",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-04-08",
      amountPayable: 11982,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "4",
      employeeName: "Rajesh Kumar",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Product Manager",
      device: "iPhone 15",
      addson: 1,
      requestedOn: "2024-04-06",
      amountPayable: 14500,
      amountDurationInMonths: 6,
      status: "rejected",
    },
    {
      key: "5",
      employeeName: "Meera Singh",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "UI/UX Designer",
      device: "iPhone 15",
      addson: 3,
      requestedOn: "2024-04-04",
      amountPayable: 21000,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "6",
      employeeName: "Rohit Sharma",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Data Scientist",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-04-02",
      amountPayable: 13500,
      amountDurationInMonths: 6,
      status: "pending",
    },
    {
      key: "7",
      employeeName: "Pooja Patel",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "DevOps Engineer",
      device: "iPhone 15",
      addson: 1,
      requestedOn: "2024-03-30",
      amountPayable: 15000,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "8",
      employeeName: "Anil Choudhary",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Backend Developer",
      device: "iPhone 15",
      addson: 2,
      requestedOn: "2024-03-28",
      amountPayable: 18500,
      amountDurationInMonths: 6,
      status: "rejected",
    },
    {
      key: "9",
      employeeName: "Kavita Rao",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Frontend Developer",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-03-26",
      amountPayable: 12000,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "10",
      employeeName: "Vikas Gupta",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "QA Engineer",
      device: "iPhone 15",
      addson: 1,
      requestedOn: "2024-03-24",
      amountPayable: 14000,
      amountDurationInMonths: 6,
      status: "pending",
    },
    {
      key: "11",
      employeeName: "Priya Desai",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "HR Manager",
      device: "iPhone 15",
      addson: 3,
      requestedOn: "2024-03-22",
      amountPayable: 21500,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "12",
      employeeName: "Suresh Iyer",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Marketing Specialist",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-03-20",
      amountPayable: 13000,
      amountDurationInMonths: 6,
      status: "rejected",
    },
    {
      key: "13",
      employeeName: "Deepika Nair",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Content Writer",
      device: "iPhone 15",
      addson: 2,
      requestedOn: "2024-03-18",
      amountPayable: 17800,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "14",
      employeeName: "Amit Singh",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Sales Manager",
      device: "iPhone 15",
      addson: 1,
      requestedOn: "2024-03-16",
      amountPayable: 14500,
      amountDurationInMonths: 6,
      status: "pending",
    },
    {
      key: "15",
      employeeName: "Neha Mehta",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Operations Manager",
      device: "iPhone 15",
      addson: 3,
      requestedOn: "2024-03-14",
      amountPayable: 22000,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "16",
      employeeName: "Vijay Rathore",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Network Engineer",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-03-12",
      amountPayable: 13500,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "17",
      employeeName: "Kiran Kulkarni",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Cloud Engineer",
      device: "iPhone 15",
      addson: 2,
      requestedOn: "2024-03-10",
      amountPayable: 19000,
      amountDurationInMonths: 6,
      status: "rejected",
    },
    {
      key: "18",
      employeeName: "Anjali Verma",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "SEO Specialist",
      device: "iPhone 15",
      addson: 0,
      requestedOn: "2024-03-08",
      amountPayable: 13200,
      amountDurationInMonths: 6,
      status: "approved",
    },
    {
      key: "19",
      employeeName: "Arjun Patil",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "System Admin",
      device: "iPhone 15",
      addson: 1,
      requestedOn: "2024-03-06",
      amountPayable: 14800,
      amountDurationInMonths: 6,
      status: "pending",
    },
    {
      key: "20",
      employeeName: "Suman Jain",
      employeePhoto: "https://xsgames.co/randomusers/avatar.php?g=male",
      designation: "Support Engineer",
      device: "iPhone 15",
      addson: 3,
      requestedOn: "2024-03-04",
      amountPayable: 22500,
      amountDurationInMonths: 6,
      status: "approved",
    },
  ];
  